# Generated by Django 4.2 on 2023-04-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на запись или новость')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL-на всякий')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Изображение')),
                ('header_type', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2')], default='h2', max_length=2, verbose_name='Выбрать тип заголовка (H1 должен быть один)')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
