# Generated by Django 4.2 on 2023-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_mobile',
            field=models.BooleanField(default=True, verbose_name='Показывать на мобильном'),
        ),
    ]
