# Generated by Django 4.2 on 2023-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_slider_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to='sliders/', verbose_name='Изображение на мобильном'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/', verbose_name='Изображение большое'),
        ),
    ]
