# Generated by Django 4.2 on 2023-05-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_slider_image_mobile_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='is_mobile',
        ),
    ]
