# Generated by Django 4.2 on 2023-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить отзыв'),
        ),
    ]
