# Generated by Django 4.2 on 2023-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0003_alter_config_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(help_text='Изображение логотипа вашей компании или организации', upload_to='logos/', verbose_name='Логотип'),
        ),
    ]
