# Generated by Django 4.2 on 2023-04-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0005_remove_config_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, help_text='Изображение логотипа вашей компании или организации', null=True, upload_to='media/', verbose_name='Логотип'),
        ),
    ]
