# Generated by Django 4.2 on 2023-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0006_config_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес вашей компании или организации', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, help_text='Email, на который будут приходить сообщения с сайта', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='config',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Телефонный номер, отображаемый на сайте', max_length=15, null=True, verbose_name='Телефонный номер'),
        ),
    ]
