# Generated by Django 4.2 on 2023-04-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0007_alter_config_address_alter_config_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='phone_url',
            field=models.CharField(blank=True, help_text='Телефонный номер, ссылка, формат: +73822908070', max_length=15, null=True, verbose_name='Телефон ссылка'),
        ),
    ]
