# Generated by Django 4.2 on 2023-04-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0008_config_phone_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Телефонный номер, отображаемый на сайте', max_length=18, null=True, verbose_name='Телефонный номер'),
        ),
    ]
