# Generated by Django 4.2 on 2023-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0009_alter_config_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='email_site',
            field=models.EmailField(blank=True, help_text='Email, который отображается на сайте', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
