# Generated by Django 4.2 on 2023-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0010_config_email_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='фэйсбук ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='facebook_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='фэйбук иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='инстаграм ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='instagram_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='инстаграм иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='другая ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='other_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='другая иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='random',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='другая-2 ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='random_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='другая-2 иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='телеграм ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='telegram_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='телеграм иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='вк ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='vk_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='вк иконка'),
        ),
        migrations.AddField(
            model_name='config',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ватсап ссылка'),
        ),
        migrations.AddField(
            model_name='config',
            name='whatsapp_img',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='ватсап иконка'),
        ),
    ]
