# Generated by Django 4.2 on 2023-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0011_config_facebook_config_facebook_img_config_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='phone_number_two',
            field=models.CharField(blank=True, help_text='Телефонный номер, отображаемый на сайте', max_length=18, null=True, verbose_name='Телефонный номер - 2'),
        ),
        migrations.AddField(
            model_name='config',
            name='phone_two_url',
            field=models.CharField(blank=True, help_text='Телефонный номер, ссылка, формат: +73822908070', max_length=15, null=True, verbose_name='Телефон ссылка - 2'),
        ),
    ]
