# Generated by Django 4.2 on 2023-04-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_contentblock_remove_page_content_ckeditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='div_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID div'),
        ),
    ]
