# Generated by Django 4.2 on 2023-04-25 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_contentblock_div_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
