# Generated by Django 4.2 on 2023-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_contentblock_title_alter_page_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_footer_menu',
            field=models.BooleanField(default=False, verbose_name='Футер меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_main_menu',
            field=models.BooleanField(default=False, verbose_name='Главное меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_mobile_menu',
            field=models.BooleanField(default=False, verbose_name='Мобильное меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_other_menu',
            field=models.BooleanField(default=False, verbose_name='Другое меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включить меню'),
        ),
    ]
