# Generated by Django 4.2 on 2023-04-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_menuitem_is_footer_menu_menuitem_is_main_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='можно указать рубрику, и будут выведены все записи из нее', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='articles.category', verbose_name='Рубрика'),
        ),
    ]
