# Generated by Django 4.2 on 2023-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_post_updated_at_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение записи'),
        ),
    ]
