# Generated by Django 4.2 on 2023-04-28 02:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_post_meta_description_post_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_ckeditor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
