# Generated by Django 4.2 on 2023-04-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_page_content_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_blocks',
            field=models.ManyToManyField(blank=True, to='articles.contentblock', verbose_name='Блоки контента'),
        ),
    ]
