# Generated by Django 4.2 on 2023-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
    ]
