# Generated by Django 4.2 on 2023-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_page_is_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
