# Generated by Django 4.2 on 2023-05-26 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_post_options_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_content_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_post', to='articles.contentblock', verbose_name='Главный блок контента'),
        ),
    ]
